# Generated by Django 4.2 on 2025-08-09 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
    ]
